### Importing required libraries

In [27]:
import pandas as pd
import numpy as np

### Loading iris dataset

In [28]:
from sklearn.datasets import load_iris
iris = load_iris()

In [29]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

The loaded iris dataset consist of four independent features:
-  sepal length
-  sepal width
-  petal length
-  petal width

In [30]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

The target column is the name of species, which are the following:
-  setosa
-  versicolor
-  virginica

Here, we will create a single level perceptron model to find the species name.

### Input features

In [31]:
X = pd.DataFrame(data = iris.data, columns = iris.feature_names)
X.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

### Output feature

In [32]:
y = pd.DataFrame(iris.target, columns = ['species'])

In [33]:
y

species
0          0
1          0
2          0
3          0
4          0
..       ...
145        2
146        2
147        2
148        2
149        2

[150 rows x 1 columns]

Here,
-  0 : setosa
-  1 : versicolor
-  2 : virginica

Suppose we only want to detect versicolor species. Then we'll simply make versicolor 1 and others 0.

In [34]:
y = (y == 1).astype(np.intc)

In [35]:
y

species
0          0
1          0
2          0
3          0
4          0
..       ...
145        0
146        0
147        0
148        0
149        0

[150 rows x 1 columns]

### **Creating simple perceptron**

For creating a simple or single level perceptron we'll be using sklearn.linear_model.Perceptron.

The Perceptron is a type of linear binary classifier that learns a decision boundary separating two classes based on a linear combination of input features.

In [36]:
from sklearn.linear_model import Perceptron

In [37]:
per_clf = Perceptron(random_state=42)
per_clf.fit(X,y)

c:\Users\KUSHAL\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Perceptron(random_state=42)

In [38]:
y_pred = per_clf.predict(X)

In [39]:
from sklearn.metrics import accuracy_score

In [40]:
accuracy_score(y, y_pred)

0.6666666666666666

### **Perceptron.coef_ :**

`per_cl_.coef_` refers to the coefficient attribute of a Perceptron classifier in scikit-learn, which represents the learned weights of the model. 

In scikit-learn, after training a `Perceptron` model, the `coef_` attribute stores the learned coefficients or weights associated with each feature. These coefficients determine the importance or contribution of each feature in the classification decision made by the Perceptron.

The `coef_` attribute is a 1D array of shape (n_features,) where n_features represents the number of input features used by the `Perceptron` model. **Each element in the array corresponds to the weight associated with a specific feature.**

In [41]:
#Slope of the perceptron
per_clf.coef_

array([[ 18.8, -41.4,  -1.4, -39.3]])

### **Perceptron.intercept_ :**

The `intercept_` attribute is specific to the Perceptron class. The `intercept_` attribute refers to the bias term of the perceptron. The bias term is an additional parameter that is added to the weighted sum before applying the activation function. It allows the perceptron to shift the decision boundary, controlling the position of the separating hyperplane.

It represents the learned bias term after training the perceptron on a given dataset. **This attribute is a single floating-point number, indicating the bias value used by the perceptron to make predictions.**

In [42]:
#Intercept of the perceptron
per_clf.intercept_

array([16.])

### Using only petal length and petal wwidth

In [43]:
X = X[['petal length (cm)', 'petal width (cm)']]

In [44]:
X.head(5)

petal length (cm)  petal width (cm)
0                1.4               0.2
1                1.4               0.2
2                1.3               0.2
3                1.5               0.2
4                1.4               0.2

In [45]:
per_clf_ = Perceptron(random_state=42)
per_clf_.fit(X,y)

c:\Users\KUSHAL\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Perceptron(random_state=42)

In [46]:
y_pred_ = per_clf_.predict(X)

In [47]:
accuracy_score(y, y_pred_)

0.6533333333333333

In [48]:
#Slope of the perceptron
per_clf_.coef_

array([[  5.8, -16.7]])

In [49]:
#Intercept of the perceptron
per_clf_.intercept_

array([-7.])